        # use collections to realize category
collections:
  my_categories:
    output: true
    permalink: /blog/category/:name/
  my_tags:
    output: true
    permalink: /blog/tag/:name/  
#sidebar names
sidebar:
  home:              主页
  about:             关于
  articles:          文章
  programming:       编程
  life:              生活
  paper:             论文
  tool:              工具
  brick:             搬砖

# Permalinks
permalink:           pretty

# Conversion
markdown:    kramdown
highlighter: rouge
excerpt_separator: "\n\n\n"

# Setup
title:               oct
name:                rainyoct
namecn:              我
tagline:             'Spacecraft'
description:         ""
url:                 https://rainyoct.github.io
baseurl:             ''
gems:
  - jekyll-feed
  - jekyll-seo-tag

# About/contact
author:
  name:              rainyoct
  url:               https://rainyoct.github.io
  email:             zry.cqu@gmail.com

sass:
  style: compressed

defaults:
  -
    scope:
      path: ""
      type: pages
    values:
      layout: page
  -
    scope:
      path: ""
      type: posts
    values:
      layout: post
  -
    scope:
      path: ""
      type: my_categories
    values:
      layout: blog_by_category
  
  -
    scope:
      path: ""
      type: my_tags
    values:
      layout: blog_by_tag
    
# Custom vars
version:             1.0.0

theme: jekyll-theme-architect